/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    events: Event;
    groups: Group;
    registrations: Registration;
    'form-assignments': FormAssignment;
    attendings: Attending;
    'team-members': TeamMember;
    tags: Tag;
    'feature-requests': FeatureRequest;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    groups: {
      members_table: 'users';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    'form-assignments': FormAssignmentsSelect<false> | FormAssignmentsSelect<true>;
    attendings: AttendingsSelect<false> | AttendingsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'feature-requests': FeatureRequestsSelect<false> | FeatureRequestsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-content': HomeContent;
    'terms-content': TermsContent;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
    'terms-content': TermsContentSelect<false> | TermsContentSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Changing roles auto-syncs the user's groups. Admin role is equivalent to President.
   */
  roles: ('visitor' | 'member' | 'staff_probation' | 'staff' | 'deputy_vp' | 'vp' | 'admin' | 'superadmin')[];
  groups?: (number | Group)[] | null;
  /**
   * Auto-syncs to the group linked to this tag.
   */
  department?: (number | null) | Tag;
  google_id?: string | null;
  image_url?: string | null;
  dob?: string | null;
  age?: number | null;
  name_thai?: {
    first_name?: string | null;
    last_name?: string | null;
    nickname?: string | null;
  };
  full_name_thai?: string | null;
  profile_complete?: boolean | null;
  name_english?: {
    first_name?: string | null;
    last_name?: string | null;
    nickname?: string | null;
  };
  academic?: {
    student_id?: string | null;
    /**
     * Auto-syncs to the group linked to this tag.
     */
    track?: (number | null) | Tag;
    /**
     * Auto-syncs to the group linked to this tag.
     */
    year?: (number | null) | Tag;
  };
  contact?: {
    line_id?: string | null;
    phone_number?: string | null;
  };
  social_media?:
    | {
        platform: string;
        handle: string;
        id?: string | null;
      }[]
    | null;
  portfolio?:
    | {
        year: '2023' | '2024' | '2025' | '2026' | '2027';
        activity: string;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  interests?: (number | Tag)[] | null;
  notification_preferences?: {
    email_opt_in?: boolean | null;
  };
  /**
   * Demo or test record. Hidden from the public site and left out of the home page counts, unless Site Settings → Show Sample Data is on.
   */
  is_sample?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  name: string;
  /**
   * Unique identifier for code references (e.g. "admin", "od", "year-1")
   */
  slug: string;
  type: 'system' | 'role' | 'department' | 'access';
  /**
   * Links this group to a Department tag.
   */
  tag?: (number | null) | Tag;
  description?: string | null;
  /**
   * Granular permissions configuration
   */
  permissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Use this field to add or remove members from the group.
   */
  members?: (number | User)[] | null;
  /**
   * Read-only table of all users belonging to this group. Click a row to view the user.
   */
  members_table?: {
    docs?: (number | User)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Editable lists used across the site. Add a row to add an option.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  kind: 'event_type' | 'department' | 'specialty' | 'academic_title' | 'year' | 'track' | 'location';
  label: string;
  /**
   * Optional. Shown on the Thai site; falls back to the English label.
   */
  label_th?: string | null;
  /**
   * Stable code for imports and seeds. Prefix by kind so codes stay unique: dept-ia, type-workshop-full, spec-urology.
   */
  slug: string;
  /**
   * Optional. Used by Locations to nest a venue under its campus.
   */
  parent?: (number | null) | Tag;
  /**
   * Lower numbers appear first.
   */
  sort_order?: number | null;
  /**
   * Uncheck to retire. Records already holding it keep it and still display it; only new pickers hide it.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  /**
   * Managed under Utilities → Tags. Adding a type is a row, not a deploy.
   */
  event_type: number | Tag;
  department?: (number | null) | Tag;
  date_begin: string;
  date_end?: string | null;
  /**
   * Managed under Utilities → Tags. Nest a venue under its campus with the Parent field.
   */
  location?: (number | null) | Tag;
  image_url?: string | null;
  description?: string | null;
  is_visible?: boolean | null;
  /**
   * Legacy info field (read-only)
   */
  info?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  subscription_form?: (number | null) | Form;
  registration_opens_at?: string | null;
  registration_closes_at?: string | null;
  /**
   * Maximum number of participants (0 = unlimited)
   */
  participant_limit?: number | null;
  is_registration_closed?: boolean | null;
  /**
   * Override automatic opening/closing times
   */
  status_override?: ('auto' | 'open' | 'closed') | null;
  /**
   * Automatically promote waiting list users when a slot opens
   */
  auto_promote?: boolean | null;
  /**
   * Limit size of waiting list (0 = unlimited)
   */
  max_waiting_list?: number | null;
  /**
   * Optional message included in the acceptance email
   */
  custom_acceptance_email?: string | null;
  /**
   * Add LINE group link, meeting location, instructions here. Only visible to users with "confirmed" status.
   */
  participant_detail?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Form users submit to request leave. Linked from the "Decline" button.
   */
  loa_form?: (number | null) | Form;
  reflection_form?: (number | null) | Form;
  is_reflection_open?: boolean | null;
  owner?: (number | null) | User;
  coordinator?: (number | null) | User;
  groups?: (number | Group)[] | null;
  /**
   * Demo or test record. Hidden from the public site and left out of the home page counts, unless Site Settings → Show Sample Data is on.
   */
  is_sample?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'radio';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: string | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'date';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            variant?: ('rating' | 'stars' | 'slider') | null;
            min?: number | null;
            max?: number | null;
            step?: number | null;
            showLabels?: boolean | null;
            minLabel?: string | null;
            maxLabel?: string | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            options: {
              label: string;
              value: string;
              id?: string | null;
            }[];
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ranking';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            options: {
              label: string;
              value: string;
              id?: string | null;
            }[];
            minSelect?: number | null;
            maxSelect?: number | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkboxGroup';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            profileField:
              | 'email'
              | 'name_english.first_name'
              | 'name_english.last_name'
              | 'name_english.nickname'
              | 'name_thai.first_name'
              | 'name_thai.last_name'
              | 'name_thai.nickname'
              | 'academic.student_id'
              | 'academic.year'
              | 'academic.track'
              | 'contact.phone_number'
              | 'contact.line_id';
            readOnly?: boolean | null;
            conditional?: {
              enabled?: boolean | null;
              action?: ('show' | 'hide') | null;
              source_field?: string | null;
              operator?: ('equals' | 'not_equals' | 'contains' | 'greater_than' | 'less_than') | null;
              value?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'userProfile';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Toggle whether this form is currently accepting new responses.
   */
  accept_responses?: boolean | null;
  /**
   * Automatically close form after this date and time (optional).
   */
  response_deadline?: string | null;
  /**
   * Automatically close form after this many submissions (optional).
   */
  response_limit?: number | null;
  publish?: {
    allow_multiple_submissions?: boolean | null;
  };
  /**
   * Message to show when the form is closed (either manually or past deadline).
   */
  closed_message?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  event: number | Event;
  user: number | User;
  status?:
    | ('subscribed' | 'applicant' | 'accepted' | 'rejected' | 'confirmed' | 'declined' | 'participant' | 'withdrawn')
    | null;
  submission?: (number | null) | FormSubmission;
  selected_at?: string | null;
  selected_by?: (number | null) | User;
  rejection_reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  user?: (number | null) | User;
  single_submission_key?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-assignments".
 */
export interface FormAssignment {
  id: number;
  form: number | Form;
  user: number | User;
  assigned_by?: (number | null) | User;
  deadline?: string | null;
  completed?: boolean | null;
  /**
   * If checked, the user cannot register for events until this form is completed.
   */
  blocks_registration?: boolean | null;
  submission?: (number | null) | FormSubmission;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendings".
 */
export interface Attending {
  id: number;
  name_thai: {
    first_name: string;
    last_name: string;
  };
  name_english: {
    first_name: string;
    last_name: string;
  };
  title?: (number | null) | Tag;
  specialty?: (number | null) | Tag;
  /**
   * Heads their specialty section with contact details shown.
   */
  is_secretary?: boolean | null;
  image_url?: string | null;
  contact?: {
    email?: string | null;
    phone_number?: string | null;
  };
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  is_visible?: boolean | null;
  /**
   * Demo or test record. Hidden from the public site and left out of the home page counts, unless Site Settings → Show Sample Data is on.
   */
  is_sample?: boolean | null;
  /**
   * Lower numbers appear first
   */
  sort_order?: number | null;
  display_name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  /**
   * Link to user profile — pulls name, image, department from their account
   */
  user: number | User;
  position: string;
  academic_year: string;
  /**
   * Uncheck to move to Hall of Fame
   */
  is_current?: boolean | null;
  /**
   * Lower numbers appear first (President = 0, VP = 1, etc.)
   */
  sort_order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-requests".
 */
export interface FeatureRequest {
  id: number;
  type: 'bug' | 'feature';
  title: string;
  description: string;
  status?: ('open' | 'planned' | 'in_progress' | 'done' | 'closed') | null;
  admin_notes?: string | null;
  submitted_by?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'form-assignments';
        value: number | FormAssignment;
      } | null)
    | ({
        relationTo: 'attendings';
        value: number | Attending;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'feature-requests';
        value: number | FeatureRequest;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  groups?: T;
  department?: T;
  google_id?: T;
  image_url?: T;
  dob?: T;
  age?: T;
  name_thai?:
    | T
    | {
        first_name?: T;
        last_name?: T;
        nickname?: T;
      };
  full_name_thai?: T;
  profile_complete?: T;
  name_english?:
    | T
    | {
        first_name?: T;
        last_name?: T;
        nickname?: T;
      };
  academic?:
    | T
    | {
        student_id?: T;
        track?: T;
        year?: T;
      };
  contact?:
    | T
    | {
        line_id?: T;
        phone_number?: T;
      };
  social_media?:
    | T
    | {
        platform?: T;
        handle?: T;
        id?: T;
      };
  portfolio?:
    | T
    | {
        year?: T;
        activity?: T;
        role?: T;
        id?: T;
      };
  interests?: T;
  notification_preferences?:
    | T
    | {
        email_opt_in?: T;
      };
  is_sample?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  event_type?: T;
  department?: T;
  date_begin?: T;
  date_end?: T;
  location?: T;
  image_url?: T;
  description?: T;
  is_visible?: T;
  info?: T;
  subscription_form?: T;
  registration_opens_at?: T;
  registration_closes_at?: T;
  participant_limit?: T;
  is_registration_closed?: T;
  status_override?: T;
  auto_promote?: T;
  max_waiting_list?: T;
  custom_acceptance_email?: T;
  participant_detail?: T;
  loa_form?: T;
  reflection_form?: T;
  is_reflection_open?: T;
  owner?: T;
  coordinator?: T;
  groups?: T;
  is_sample?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  tag?: T;
  description?: T;
  permissions?: T;
  members?: T;
  members_table?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  status?: T;
  submission?: T;
  selected_at?: T;
  selected_by?: T;
  rejection_reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-assignments_select".
 */
export interface FormAssignmentsSelect<T extends boolean = true> {
  form?: T;
  user?: T;
  assigned_by?: T;
  deadline?: T;
  completed?: T;
  blocks_registration?: T;
  submission?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendings_select".
 */
export interface AttendingsSelect<T extends boolean = true> {
  name_thai?:
    | T
    | {
        first_name?: T;
        last_name?: T;
      };
  name_english?:
    | T
    | {
        first_name?: T;
        last_name?: T;
      };
  title?: T;
  specialty?: T;
  is_secretary?: T;
  image_url?: T;
  contact?:
    | T
    | {
        email?: T;
        phone_number?: T;
      };
  bio?: T;
  is_visible?: T;
  is_sample?: T;
  sort_order?: T;
  display_name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  user?: T;
  position?: T;
  academic_year?: T;
  is_current?: T;
  sort_order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  kind?: T;
  label?: T;
  label_th?: T;
  slug?: T;
  parent?: T;
  sort_order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-requests_select".
 */
export interface FeatureRequestsSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  description?: T;
  status?: T;
  admin_notes?: T;
  submitted_by?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        radio?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        date?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              variant?: T;
              min?: T;
              max?: T;
              step?: T;
              showLabels?: T;
              minLabel?: T;
              maxLabel?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ranking?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        checkboxGroup?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              minSelect?: T;
              maxSelect?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
        userProfile?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              profileField?: T;
              readOnly?: T;
              conditional?:
                | T
                | {
                    enabled?: T;
                    action?: T;
                    source_field?: T;
                    operator?: T;
                    value?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  accept_responses?: T;
  response_deadline?: T;
  response_limit?: T;
  publish?:
    | T
    | {
        allow_multiple_submissions?: T;
      };
  closed_message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  user?: T;
  single_submission_key?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  /**
   * The banner at the top of the home page. Blank fields fall back to the built-in copy.
   */
  hero?: {
    /**
     * Small line above the title.
     */
    eyebrow?: string | null;
    heading?: string | null;
    /**
     * Sits under the title, set in the display face. Used for the Thai name.
     */
    subheading?: string | null;
    /**
     * The paragraph above the buttons.
     */
    lead?: string | null;
    /**
     * Hero image. Defaults to /assets/beta.jpg.
     */
    imageUrl?: string | null;
    /**
     * Up to two. The first is solid, the second outlined. Leave empty for the default pair.
     */
    ctas?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Headings and captions on the home page. The numbers beside the captions are counted live from the database — only the wording is editable here. Blank fields keep the built-in wording.
   */
  labels?: {
    /**
     * Under the big number in the stat band.
     */
    memberStat?: string | null;
    sessionStat?: string | null;
    advisorStat?: string | null;
    /**
     * Heads the block of forms a signed-in student still owes. Hidden when they owe none.
     */
    pendingHeading?: string | null;
    upcomingHeading?: string | null;
    pastHeading?: string | null;
    /**
     * The link to the full events list, beside the past events heading.
     */
    pastLink?: string | null;
  };
  /**
   * The alternating image/text story blocks under the hero. Order here is order on the page.
   */
  sections?:
    | {
        /**
         * Small label shown above the section title.
         */
        kicker?: string | null;
        heading: string;
        body: string;
        /**
         * Optional image URL for this section.
         */
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-content".
 */
export interface TermsContent {
  id: number;
  /**
   * Optional intro paragraph shown under the page heading.
   */
  intro?: string | null;
  sections?:
    | {
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Full name. Used in the header, footer, and page titles.
   */
  siteName?: string | null;
  /**
   * The short mark beside the logo and in the footer.
   */
  shortName?: string | null;
  /**
   * Used as the default <meta name="description"> for the public site.
   */
  metaDescription?: string | null;
  /**
   * Controls whether language switching is enabled on the public site.
   */
  enableI18n?: boolean | null;
  /**
   * Reveals every record flagged "Sample Data" on the public site and in the home page counts. Leave off outside of a demo.
   */
  showSampleData?: boolean | null;
  /**
   * Opens the public self-service password-reset path and sends an email through our (quota-limited) Resend account for every request. Normally leave this off; switch it on only while someone needs to recover an account, then switch it back off.
   */
  enablePasswordReset?: boolean | null;
  /**
   * Posters vary in shape — a portrait Drive upload next to a wide banner. "Shrink image to fit" keeps every card the same size and letterboxes the image inside it. "Crop image to fill card" keeps that same card size but crops the poster to fill it with no letterboxing. "Expand card to fit image" drops the fixed shape and lets each card grow to the poster’s own proportions, so the grid loses its even rows.
   */
  eventCardImageDisplay?: ('expand-card' | 'shrink-img-to-fit' | 'crop-to-fit') | null;
  /**
   * How the poster on an event’s own page sizes. "Shrink image to fit" keeps the banner’s fixed shape and letterboxes the image inside it. "Crop image to fill" keeps that same shape but crops the poster to fill it with no letterboxing. "Full size" shows the poster at its own proportions instead.
   */
  eventDetailImageDisplay?: ('full-size' | 'shrink-img-to-fit' | 'crop-to-fit') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subheading?: T;
        lead?: T;
        imageUrl?: T;
        ctas?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  labels?:
    | T
    | {
        memberStat?: T;
        sessionStat?: T;
        advisorStat?: T;
        pendingHeading?: T;
        upcomingHeading?: T;
        pastHeading?: T;
        pastLink?: T;
      };
  sections?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        imageUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-content_select".
 */
export interface TermsContentSelect<T extends boolean = true> {
  intro?: T;
  sections?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  shortName?: T;
  metaDescription?: T;
  enableI18n?: T;
  showSampleData?: T;
  enablePasswordReset?: T;
  eventCardImageDisplay?: T;
  eventDetailImageDisplay?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}